name: 'Billing Project Promotion Tests - WIP'

on:
  push:
    branches:
      - "arh-wor-1222-bp-test-action"

jobs:
  create-billing-project:
    runs-on: ubuntu-latest
    container:
      image: gcr.io/broad-dsp-gcr-public/azure-workspace-tools:960c6a7
    steps:
      - name: Create the billing project
        run: python billing_project.py

